package no.rune.typecompanion;

import no.rune.typecompanion.ext.TypeCompanionGeneratorExtension;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;
import org.burningwave.core.assembler.ComponentSupplier;
import org.burningwave.core.classes.ClassCriteria;
import org.burningwave.core.classes.SearchConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Path;
import java.util.Collection;
import java.util.List;
import java.util.ServiceLoader;
import java.util.ServiceLoader.Provider;
import java.util.Set;
import java.util.function.Predicate;
import java.util.stream.Stream;

import static java.util.Objects.requireNonNullElseGet;
import static java.util.function.Predicate.not;
import static java.util.stream.Collectors.toUnmodifiableSet;
import static java.util.stream.Stream.concat;
import static no.rune.typecompanion.Collectors.multiGroupingBy;
import static org.apache.maven.plugins.annotations.LifecyclePhase.GENERATE_TEST_SOURCES;
import static org.apache.maven.plugins.annotations.ResolutionScope.COMPILE;

@Mojo(
        name = GenerateTypeCompanionsMojo.GOAL_NAME,
        defaultPhase = GENERATE_TEST_SOURCES,
        requiresDependencyResolution = COMPILE)
public class GenerateTypeCompanionsMojo extends CodeGeneratorBaseMojo {

    static final String GOAL_NAME = "generate";

    private static final Logger LOG = LoggerFactory.getLogger(GenerateTypeCompanionsMojo.class);

    /**
     * Specifies the fully qualified class names of the
     * types to generate companions for for.
     */
    @Parameter(property = PLUGIN_CONF_PROP_PREFIX + "includes")
    private Set<String> includes;


    /**
     * Specify which packages (includes any sub packages) to scan for source types.
     */
    @Parameter(
            defaultValue = "${project.groupId}",
            property = PLUGIN_CONF_PROP_PREFIX + "scanPackages")
    private Set<String> scanPackages;


    /**
     * Set if scanning for source types is enabled or not.
     */
    @Parameter(required = true,
            defaultValue = "true",
            property = PLUGIN_CONF_PROP_PREFIX + "scanEnabled")
    private boolean scanEnabled;


    /**
     * Specifies fully qualified class names of types to
     * exclude from type companion generators.
     */
    @Parameter(property = PLUGIN_CONF_PROP_PREFIX + "excludes")
    private Set<String> excludes;


    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        if (requireNonNullElseGet(skipForPackaging, Set::of).contains(mavenProject.getPackaging())) {
            LOG.info("Skipping " + mavenProject.getPackaging() + " module");
            return;
        }

        var generators = generators();
        if (generators.isEmpty()) {
            LOG.info("Nothing generated, because no generators could be located");
            return;
        }

        var sourceTypesAssignedToGenerators = generators.stream()
                .map(generator -> (Predicate<Class<?>>) generator::applicableFor)
                .reduce(Predicate::or)
                .map(this::resolveSourceTypes)
                .orElseGet(Stream::empty)
                .collect(multiGroupingBy(generators, TypeCompanionGeneratorExtension::applicableFor));

        if (sourceTypesAssignedToGenerators.isEmpty()) {
            LOG.info("Nothing generated, because no source types was assigned to any of the generators {}", generators);
        } else {
            Path outputDirectory = outputDirectory().path();
            LOG.info("Generating type companions in {}", outputDirectory);
            sourceTypesAssignedToGenerators
                .forEach((generator, sourceTypes) -> {
                    var fileWriter = new JavaFileWriter(outputDirectory);
                    var writtenFiles = sourceTypes.stream()
                            .map(generator.codeGenerator()::generateFor)
                            .map(compilationUnit -> {
                                try {
                                    return fileWriter.writeToFile(compilationUnit);
                                } catch (IOException e) {
                                    throw new UncheckedIOException(
                                            "Unable to write " + compilationUnit + " to file, " +
                                            "because " + e.getClass().getSimpleName() + ": " + e.getMessage(), e);
                                }
                            })
                            .sorted()
                            .toList();

                    if (writtenFiles.isEmpty()) {
                        LOG.warn("Nothing generated by {}!", generator.getClass().getSimpleName());
                    } else {
                        LOG.info("Generated by {}:", generator.getClass().getSimpleName());
                        for (var writtenFile : writtenFiles) {
                            LOG.info("  {}", outputDirectory.relativize(writtenFile));
                        }
                        LOG.info("Total files written: {}", writtenFiles.size());
                    }
                });
        }


    }

    private List<TypeCompanionGeneratorExtension> generators() {
        return ServiceLoader.load(TypeCompanionGeneratorExtension.class).stream().map(Provider::get).toList();
    }

    @Override
    protected OutputDirectory outputDirectory() {
        var outputDirectory = super.outputDirectory();
        if (!outputDirectory.exists()) {
            outputDirectory.create();
            LOG.warn("""
                Directory {} was created because it did not already exist, but you need to use \
                the {} goal in order to include it as test sources for the project.\
                """,
                outputDirectory.path(), PrepareOutputDirectoryMojo.GOAL_NAME);

            LOG.info("""
                In order to include the generated code as compiled test code, \
                it is required to configure the goal '{}' to create this directory \
                separately before the '{}' goal is run. Please ensure the plugin's \
                execution is configured like this:

                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-output-directory</goal>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                <execution>

                If you are running the goal directly from the command line, you can try prepending \
                the {} goal with the {} goal:

                 mvn type-companions:{} type-companions:{}

                See the README at https://github.com/runeflobakk/type-companions for further details on \
                configuring and/or running standalone goals of the type-companions-maven-plugin.
                """,
                PrepareOutputDirectoryMojo.GOAL_NAME, GenerateTypeCompanionsMojo.GOAL_NAME,
                GenerateTypeCompanionsMojo.GOAL_NAME, PrepareOutputDirectoryMojo.GOAL_NAME,
                PrepareOutputDirectoryMojo.GOAL_NAME, GenerateTypeCompanionsMojo.GOAL_NAME);
        }
        return outputDirectory;
    }


    private Stream<Class<?>> resolveSourceTypes(Predicate<Class<?>> applicableTypes) {
        ClassLoader classLoader = buildProjectClassLoader(mavenProject, this.getClass().getClassLoader());

        Stream<Class<?>> scannedTypes;
        if (scanEnabled) {
            scannedTypes = scanForClasses(classLoader, scanPackages, applicableTypes);
        } else {
            LOG.info("Not scanning for source types");
            scannedTypes = Stream.empty();
        }

        Stream<Class<?>> configuredTypes;
        if (includes != null && !includes.isEmpty()) {
            configuredTypes = includes.stream()
                    .filter(not(String::isBlank))
                    .map(String::trim)
                    .<Class<?>>map(className -> load(className, classLoader));
        } else {
            if (!scanEnabled) {
                LOG.info("No specific types configured for inclusion");
            }
            configuredTypes = Stream.empty();
        }

        var foundTypes = concat(scannedTypes, configuredTypes).distinct();
        if (excludes != null && !excludes.isEmpty()) {
            var sanitizedExcludes = excludes.stream().filter(not(String::isBlank)).map(String::trim).collect(toUnmodifiableSet());
            return foundTypes.filter(r -> {
                if (sanitizedExcludes.contains(r.getName())) {
                    LOG.info("Excluding {}", r.getName());
                    return false;
                } else {
                    return true;
                }
            });
        } else {
            return foundTypes;
        }
    }

    private static Stream<Class<?>> scanForClasses(ClassLoader classLoader, Collection<String> packageNames, Predicate<Class<?>> applicableTypes) {
        packageNames = packageNames.stream().filter(not(String::isBlank)).map(String::trim).distinct().toList();
        if (packageNames.isEmpty()) {
            LOG.debug("No packages configured for scanning");
            return Stream.empty();
        }

        LOG.info("Scanning packages {} for source types", packageNames);
        var allApplicableTypesInClassLoader = SearchConfig
                .byCriteria(ClassCriteria.create().allThoseThatMatch(applicableTypes))
                .useAsParentClassLoader(classLoader)
                .addResources(classLoader, packageNames.stream().map(p -> p.replace('.', '/')).toList());

        var classHunter = ComponentSupplier.getInstance().getClassHunter();
        try (var searchResult = classHunter.findBy(allApplicableTypesInClassLoader)) {
            return searchResult.getClasses().stream();
        } catch (RuntimeException e) {
            throw new IllegalStateException(
                    "There was an error scanning for source types in package(s) " + packageNames + ": " +
                    e.getClass().getSimpleName() + " '" + e.getMessage() + "'. Ensure that the packages " +
                    "are correctly defined and exists.", e);
        }
    }

    private static <C> Class<?> load(String className, ClassLoader classLoader) {
        try {
            return classLoader.loadClass(className);
        } catch (ClassNotFoundException e) {
            throw new IllegalArgumentException(
                    "Unable to resolve Class from " + className +
                    ", because " + e.getClass().getSimpleName() + ": " + e.getMessage(), e);
        }
    }

    private static ClassLoader buildProjectClassLoader(MavenProject project, ClassLoader parent) {
        try {
            List<String> classpathElements = project.getCompileClasspathElements();
            URL urls[] = new URL[classpathElements.size()];
            for ( int i = 0; i < classpathElements.size(); ++i ) {
                urls[i] = new File(classpathElements.get( i ) ).toURI().toURL();
            }
            return new URLClassLoader(urls, parent);
        } catch (Exception e) {
            throw new RuntimeException(
                    "Unable to build classloader for resolving source types, " +
                    ", because " + e.getClass().getSimpleName() + ": " + e.getMessage(), e);
        }
    }

}
