<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.github.runeflobakk</groupId>
        <artifactId>type-companions</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>type-companions-generator-testing</artifactId>

    <name>Type Companions Generator Test Utilities</name>
    <description>Various utilities to help test Type Companion code generators</description>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.github.runeflobakk</groupId>
            <artifactId>type-companions-generator-spi</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.testing.compile</groupId>
            <artifactId>compile-testing</artifactId>
            <version>0.23.0</version>
        </dependency>
    </dependencies>

</project>
